### ISSUE TITLE
Common user

### ISSUE THREAD

**Issue by Data-Designer** [FengZhu-Joey/GA-DTCDR#3]
Hi. I am confused about overlapping user IDs. In this code, I only see fully overlapping user IDs, not partial overlapping

**Comment by Data-Designer** [comment]
It seems that the source code does not distinguish between common user and distinct user, but directly integrates the representations of the two domains in Batch?

**Comment by FengZhu-Joey** [comment]
We have serialized the user IDs of the two domains. Common users from different domains have duplicate IDs, while for distinct users, their IDs are different. All users from different domains are in the same user-space. In this way, it will be easy to integrate the embeddings of common users. For example, if domain A has user ids: [1, 2], and domain B has user IDs [1, 3], then the joint user space is [1, 2, 3]. Thus, for domain A, we have three user embeddings [e_1^a, e_2^a, e_3^a], and for domain B, we have three user embeddings [e_1^b, e_2^b, e_3^b].

**Comment by Data-Designer** [comment]
Thanks. Your reply helps me  a lot.
