### ISSUE TITLE
doc2vec

### ISSUE THREAD

**Issue by Littlepijiang** [FengZhu-Joey/GA-DTCDR#4]
hi！
I want to know why self.model_D2V = None and can u share the codes of doc2vec？

**Comment by FengZhu-Joey** [comment]
Hi, you can find the code of doc2vec in "Doc2vec_DoubanDatasets.py".

**Comment by Littlepijiang** [comment]
Thank you for your reply.
I have another question. Does the generation of some subsets such as movie_subset_5 and moviereviews_subset_5 in "Doc2vec_DoubanDatasets.py" have any requests？ and in a subset，the UID2 or user_id whether need to renumber？
